### ISSUE TITLE
Rog ally up tdp to 45?

### ISSUE THREAD

**Issue by ripplingsnake** [mengmeet/PowerControl#20]
Hello can we please have the ally upped to 45 watt or tell us what file to modify?. The ally has great cooling and I can run at 50 watts in windows ?

**Comment by mjsf12** [comment]
if you unlock you can.
how to:
https://www.youtube.com/watch?v=pTvWJey9ku8

**Comment by ripplingsnake** [comment]
I have smokeless already the problem is power control does not work on nobara steam :) new issue

**Comment by ripplingsnake** [comment]
Yes I can change tpd with ryzenadj up to 50 watts, I think I with nobara it’s a permissions issue MarcOn 11 Nov 2023, at 19:08, Marcilio Junior ***@***.***> wrote:﻿
This appears to be a RyzenAdj issue. Can you make the changes directly with RyzenAdj?
