### ISSUE TITLE
Crashing when opening AC6 with this plugin enabled

### ISSUE THREAD

**Issue by gmartins-henrique** [mengmeet/PowerControl#21]
Tested on
- ChimeraOS 43/44
- Proton 8
- AyaNeo 2D

When opening Armored Core 6, after EAC, the screen flashes white, and the game closes. If I disable settings on the plugin configuration, game launches just fine.

**Comment by gmartins-henrique** [comment]
I meant AyaNeo 2S

**Comment by honjow** [comment]
If smt is closed, try opening it

**Comment by gmartins-henrique** [comment]
What is SMT?
