### ISSUE TITLE
更新安装教程

### ISSUE THREAD

**Issue by so1ar** [mengmeet/PowerControl#23]
我按照Readme的安装教程安装时发现decky-loader的插件目录是只读的，无法手动复制文件过去，如果手动修改目录权限，那么在游戏模式中decky-loader就进不去设置界面，只能卸载并重新安装decky-loader。

我摸索出来的一个可行的安装方法是下载插件后解压再重新压缩成zip格式，decky-loader设置里打开开发者模式，再去到开发者模式里选择从zip压缩文件安装插件。

希望能够更新一下Readme的安装教程并在release中提供zip格式的压缩包文件

**Comment by honjow** [comment]
不用重新安装啊。你只要重启decky的服务，他就会自己把权限改回来。

**Comment by honjow** [comment]
更新了手动安装说明，并且添加了一个一键安装脚本
