### ISSUE TITLE
ROG Ally - zero control on Nobara/Fedora

### ISSUE THREAD

**Issue by matte-schwartz** [mengmeet/PowerControl#24]
I have not been able to get PowerControl functional on Nobara, a Fedora distribution. The plugin installation seems to go fine and the plugin is available in Decky loader after installation, but none of the controls in the plugin actually affect the TDP or GPU. I have tried multiple older versions of PowerControl and they have the same issue. It still mostly works on ChimeraOS up to 30W from what I've heard other people say.

if it's helpful for reference, I've been using a [modified fork](https://github.com/hicder/PowerTools) of PowerTools to control the TDP. It has its own issues with power profile settings over 30W but it provides adequate control over TDP.

**Comment by honjow** [comment]
Check if there is any abnormal information in these two logs. `/tmp/PowerControl_py.log`  `/tmp/powerControl_sh.log`
