### ISSUE TITLE
7840U has new SMT topology 

### ISSUE THREAD

**Issue by adolfotregosa** [mengmeet/PowerControl#27]
grep -H . /sys/devices/system/cpu/cpu*/topology/thread_siblings_list                   
        
/sys/devices/system/cpu/cpu0/topology/thread_siblings_list:0,8
/sys/devices/system/cpu/cpu1/topology/thread_siblings_list:1,9
/sys/devices/system/cpu/cpu2/topology/thread_siblings_list:2,10
/sys/devices/system/cpu/cpu3/topology/thread_siblings_list:3,11
/sys/devices/system/cpu/cpu4/topology/thread_siblings_list:4,12
/sys/devices/system/cpu/cpu5/topology/thread_siblings_list:5,13
/sys/devices/system/cpu/cpu6/topology/thread_siblings_list:6,14
/sys/devices/system/cpu/cpu7/topology/thread_siblings_list:7,15
/sys/devices/system/cpu/cpu8/topology/thread_siblings_list:0,8
/sys/devices/system/cpu/cpu9/topology/thread_siblings_list:1,9
/sys/devices/system/cpu/cpu10/topology/thread_siblings_list:2,10
/sys/devices/system/cpu/cpu11/topology/thread_siblings_list:3,11
/sys/devices/system/cpu/cpu12/topology/thread_siblings_list:4,12
/sys/devices/system/cpu/cpu13/topology/thread_siblings_list:5,13
/sys/devices/system/cpu/cpu14/topology/thread_siblings_list:6,14
/sys/devices/system/cpu/cpu15/topology/thread_siblings_list:7,15

this means that disabling SMT, actual cores should be from 0 to 7 (not 0 2 4 6 8 etc) and with SMT threads from 8 to 15

**Comment by mjsf12** [comment]
I think the Z1 Extreme also has the same topology:

> [gamer@rogally Downloads]$ grep -H . /sys/devices/system/cpu/cpu*/topology/thread_siblings_list
> /sys/devices/system/cpu/cpu0/topology/thread_siblings_list:0,8
> /sys/devices/system/cpu/cpu10/topology/thread_siblings_list:2,10
> /sys/devices/system/cpu/cpu11/topology/thread_siblings_list:3,11
> /sys/devices/system/cpu/cpu12/topology/thread_siblings_list:4,12
> /sys/devices/system/cpu/cpu13/topology/thread_siblings_list:5,13
> /sys/devices/system/cpu/cpu14/topology/thread_siblings_list:6,14
> /sys/devices/system/cpu/cpu15/topology/thread_siblings_list:7,15
> /sys/devices/system/cpu/cpu1/topology/thread_siblings_list:1,9
> /sys/devices/system/cpu/cpu2/topology/thread_siblings_list:2,10
> /sys/devices/system/cpu/cpu3/topology/thread_siblings_list:3,11
> /sys/devices/system/cpu/cpu4/topology/thread_siblings_list:4,12
> /sys/devices/system/cpu/cpu5/topology/thread_siblings_list:5,13
> /sys/devices/system/cpu/cpu6/topology/thread_siblings_list:6,14
> /sys/devices/system/cpu/cpu7/topology/thread_siblings_list:7,15
> /sys/devices/system/cpu/cpu8/topology/thread_siblings_list:0,8
> /sys/devices/system/cpu/cpu9/topology/thread_siblings_list:1,9


I confirmed it by checking the /proc/cpuinfo as well:

> [gamer@rogally Downloads]$ grep -E 'processor|core id' /proc/cpuinfo
> processor	: 0
> core id		: 0
> processor	: 1
> core id		: 1
> processor	: 2
> core id		: 2
> processor	: 3
> core id		: 3
> processor	: 4
> core id		: 4
> processor	: 5
> core id		: 5
> processor	: 6
> core id		: 6
> processor	: 7
> core id		: 7
> processor	: 8
> core id		: 0
> processor	: 9
> core id		: 1
> processor	: 10
> core id		: 2
> processor	: 11
> core id		: 3
> processor	: 12
> core id		: 4
> processor	: 13
> core id		: 5
> processor	: 14
> core id		: 6
> processor	: 15
> core id		: 7

**Comment by honjow** [comment]
The new version has implemented SMT operations based on CPU topology.

**Comment by adolfotregosa** [comment]
thank you, working. I still have gpu clocks NaN issue but ill open up a new issue
