### ISSUE TITLE
ayaneo air plus (6800U) fan control and CPU clock boost issues. 风扇控制以及cpu睿频问题。

### ISSUE THREAD

**Issue by HIBIYAK** [mengmeet/PowerControl#28]
Hi! I have two 6800U machines (Ayaneo 2 and Ayaneo Air Plus). Fan control is available on Ayaneo 2, but the Air Plus lacks fan control options. Additionally, the CPU clock boost cannot be disabled on both of these machines. Both machines are running the Chimera OS. 

你好，我有两台6800U掌机（ayaneo 2 和 ayaneo air plus）。在ayaneo 2 上可以控制风扇，但是air plus 没有风扇控制的选项。同时，这两台掌机的CPU睿频都无法被关闭。两台掌机都装了奇美拉OS。

**Comment by honjow** [comment]
Because we don't know the relevant parameters for controlling the AirPlus fan, we can't control it.
