### ISSUE TITLE
Cpu clock stuck at minimum.

### ISSUE THREAD

**Issue by adolfotregosa** [mengmeet/PowerControl#33]
Latest steam, powercontrol 2.1.3 and decky pre release.

Cpu stays at minimum frequency as soon powercontrol is loaded. Also tdp does not seam to be working with latest steam. That seams to be the issue, tdp is stuck at minimum ??

GPU clocks are working. I can manually change them.

![20231214_094033](https://github.com/mengmeet/PowerControl/assets/7437931/01b92204-e150-44e7-9fc2-efd81a007bbc)

[PowerControl_py.log](https://github.com/mengmeet/PowerControl/files/13671566/PowerControl_py.log)

**Comment by colinchen1987** [comment]
I have the same issue on GPDWIN Mini
after same investigation,it seems to have to do with the cpu scaling governor acpi_cpufreq
go to ~/homebrew/plugins/PowerControl/backend/cpu.py, change line 205 to file.write('enable'), line 206 to os.system("modprobe amd_pstate"), seems to fix my problem. Though selecting gpu frenquency adjust with load(slider at furthest right) brings the cpu back down to 548MHz after a while, so it's only a band-aid solution.

**Comment by honjow** [comment]
Version 2.2.0 has fixed this issue. Please test it. If the problem persists, reopen this issue

**Comment by adolfotregosa** [comment]
Sorry, still doing it

**Comment by honjow** [comment]
> Sorry, still doing it [PowerControl_py.log](https://github.com/mengmeet/PowerControl/files/13676046/PowerControl_py.log)

Have you tried rebooting?

**Comment by adolfotregosa** [comment]
> > Sorry, still doing it [PowerControl_py.log](https://github.com/mengmeet/PowerControl/files/13676046/PowerControl_py.log)
> 
> Have you tried rebooting?

of course

**Comment by honjow** [comment]
What system, what version? Any information about the kernel?

**Comment by adolfotregosa** [comment]
> What system, what version? Any information about the kernel?

indeed kernel as something to do with it. . I'll gather more info and report back

**Comment by adolfotregosa** [comment]
ok. Can you try any kernel 6.6.7 ? I have two 6.6.7 kernels. One it still gets stuck at minimum the other after sometime mangohud stops reporting cpu clocks correctly . It stays fixed or the refresh rate is really slow. Something breaks
