### ISSUE TITLE
Dunno why... mangohud conflict ?

### ISSUE THREAD

**Issue by adolfotregosa** [mengmeet/PowerControl#36]
Powercontrol is running well now but for what ever reason it makes mangohud cpu frequency reporting freeze in place or go to zero, either one eventually. 

Any suggestions ?

**Comment by honjow** [comment]
Try version 2.2.2.

**Comment by adolfotregosa** [comment]
> Try version 2.2.2.

it seams to be fixed. I'll keep an eye. Thank you !
