### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by dctr** [mengmeet/PowerControl#4]
Hello,

Thanks for doing this, I much appreciate your work!

Would it be possible to implement support for multiple languages? If you implement the support, I am happy to translate localization files. In my house, we have speakers of English and German, and someone who understands Mandarin, so we could translate language resource files.

Cheers

**Comment by dctr** [comment]
Here you go: https://github.com/Gawah/PowerControl/pull/5 :-)

**Comment by Gawah** [comment]
I've been busy making fan functions and I'm almost done now. A lot of new strings have been added. Can you help me see if the English and German translations are normal

**Comment by dctr** [comment]
Hello, sorry for the late reply. I was very busy the last weeks. I can have a look at it over Easter. 

Just the localisations.ts file I assume?

**Comment by dctr** [comment]
Just has a look at the localisations: https://github.com/Gawah/PowerControl/pull/8

If there are any other places I should look at, let me know.
