### ISSUE TITLE
power control interface just shows spinning steam logo 

### ISSUE THREAD

**Issue by ripplingsnake** [mengmeet/PowerControl#51]
seems to happen randomly on rog ally switching from desktop to game mode and sometimes on reboot, opening power control just shows spinning steam logo and no controls , manjaro linux

**Comment by semakusut** [comment]
it's happenn on nobara too

**Comment by ripplingsnake** [comment]
It seems the only way to have the ui load is to go into decky plug ins and reload power control plug in

**Comment by honjow** [comment]
Which version is it? Or try updating to 2.4.4 to see if it resolves the issue.

**Comment by semakusut** [comment]
2.4.3 already updated to 2.4.4 its worked fine now, thx

**Comment by ripplingsnake** [comment]
Thank you will check tonight, a few users have said there fans ramp up even if set at a low rpm but I assume that’s the bios overriding the fan settings?

**Comment by honjow** [comment]
> Thank you will check tonight, a few users have said there fans ramp up even if set at a low rpm but I assume that’s the bios overriding the fan settings?

Device and system information ？

**Comment by ripplingsnake** [comment]
Rog ally bios 336 manjaro arch Linux

**Comment by alwdark** [comment]
Thanks for the great plugin!
The TDP toggle is switched off automatically in Steam performance tab for a while on 2.4.4.
2.3.X is normal.

GPD Win4  with ChimeraOS 45.

**Comment by honjow** [comment]
> Thanks for the great plugin! The TDP toggle is switched off automatically in Steam performance tab for a while on 2.4.4. 2.3.X is normal.
> 
> GPD Win4 with ChimeraOS 45.

If you encounter any other issues, please post a separate issue.
