### ISSUE TITLE
The TDP toggle is switched off automatically in Steam performance tab for a while

### ISSUE THREAD

**Issue by alwdark** [mengmeet/PowerControl#53]
Thanks for the great plugin!
The TDP toggle is switched off automatically in Steam performance tab for a while on 2.4.4.
2.3.X is normal.

GPD Win4 with ChimeraOS 45.

![20240313_205516-ANIMATION](https://github.com/mengmeet/PowerControl/assets/69226911/18820e2a-0b06-46f5-8ad6-8e2d65636cbe)

BTW, if I active original GPU control, and setting GPU frequency such as adaptive, which one will be used?
Thank you.

**Comment by honjow** [comment]
开关问题我这里没有办法复现。尝试卸载完全新安装，或者手动安装到旧版本再看看
gpu开原生控制条的情况，只有再原生档位才是用原生设置的条。只能固定频率。效果和关掉原生控制时的固定频率是一样的

**Comment by alwdark** [comment]
感謝回覆!
還是我可以試試將已存在的設定清除再測試2.4.4版是否還有此問題?
請問要如何清除所有已存在的設定呢?
將Powercontrol v2.4.4移除再安裝v2.3.2的確沒有這問題發生，但是還是可以load之前的TDP與風扇設置。
之前將v2.3.2更新至v2.4.2時該問題已經發生，但是像之前的issue描述進入plugin的設置頁面只會看到Steam的讀取圖，所以當時不確定是哪裡的問題。
v2.4.4已將設置頁出現Steam的讀取圖問題解決了。

**Comment by honjow** [comment]
更新了2.4.5，添加了一个重置所有设置的按钮。还有在初始化异常的时候重置设置的机制。看看能不能解决你的问题

**Comment by alwdark** [comment]
Hi, 更新了v2.4.5與v2.4.6結果設置頁又出現Steam的讀取圖問題，在插件重新載入後雖然可以進入PowerControl設置頁，但是創建風扇與其他設定後皆不會保存。
同時在Steam的效能頁籤會出現錯誤訊息。
試著在重新載入後的設置頁重置設定，但是重開機後狀況依舊。
![20240314_211543](https://github.com/mengmeet/PowerControl/assets/69226911/fcfd6e2a-16f6-48b6-9915-a271116da343)
![20240314_211000](https://github.com/mengmeet/PowerControl/assets/69226911/4223697a-7444-41b2-a867-982f7c0fcdf6)

**Comment by alwdark** [comment]
剛測試v2.4.7，狀況一樣，謝謝

**Comment by alwdark** [comment]
你好，查看除錯工具，似乎是tdp_limit_min沒有正確賦值
![20240314_231355](https://github.com/mengmeet/PowerControl/assets/69226911/a649cdee-eaf7-4b80-827e-f8c7c6f3ec67)

**Comment by honjow** [comment]
再试试最新版，看看解决了没有

**Comment by alwdark** [comment]
你好，v2.4.8設置頁無法進入。
![20240315_074621](https://github.com/mengmeet/PowerControl/assets/69226911/2c78491d-4973-41be-a9a3-b6681e91228c)

**Comment by honjow** [comment]
> 你好，v2.4.8設置頁無法進入。 ![20240315_074621](https://private-user-images.githubusercontent.com/69226911/313024912-2c78491d-4973-41be-a9a3-b6681e91228c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjgwMDMsIm5iZiI6MTcxMDQ2NzcwMywicGF0aCI6Ii82OTIyNjkxMS8zMTMwMjQ5MTItMmM3ODQ5MWQtNDk3My00MWJlLWE5YTMtYjY2ODFlOTEyMjhjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxNTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTMyZDQxMmMxOTkwNWMyMjRjNzM2YjljNWMwZGZmOWVjZWQwZGQ0Yjc2NDBiNTEyNjJmMDg1OTViNGMxYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUBX45fsi19FX-WmDmg0BzcWMm2jkzc8J_Jc8ScsHco)

删掉，再重新安装呢

**Comment by honjow** [comment]
还是不行的话，到你上面这个调试页面，Application -> Storage -> Local Storage 里面。找到 Key 为PowerControl 的数据项，删掉

**Comment by alwdark** [comment]
你好，猜測主因為冷開機進入系統時，當下class QAMPatch/TDPPatch取到的perfStore.msgLimits與 perfStore.msgSettingsPerApp為undefined導致的，因此賦值error。
以下為TDPPatch init()印出this.perfStore, this.perfStore.msgLimits, this.perfStore.msgSettingsPerApp, this.perfStore.m_msgState的結果
![20240315_123057](https://github.com/mengmeet/PowerControl/assets/69226911/27e51027-5058-4cbb-a7b8-560091d0c257)

**Comment by honjow** [comment]
搞不明白。这里没法复现这个错误。前面只是修改了配置数据保存问题而已

**Comment by alwdark** [comment]
此狀況應該是2.3.2->2.4.X新增的代碼，因此也符合2.3.2正常。可能也是2.4.X起會載入失敗顯示steam loading圖片的原因，看代碼之前是透過Backend.applyTDP賦值

**Comment by honjow** [comment]
> 此狀況應該是2.3.2->2.4.X新增的代碼，因此也符合2.3.2正常。可能也是2.4.X起會載入失敗顯示steam loading圖片的原因，看代碼之前是透過Backend.applyTDP賦值

还是很奇怪。我在chimeraos和steamos中都没复现这个问题。可能是中途有哪个版本有问题导致存入了什么错误的数据。有试过我上面说的清除 Local Storage 吗。或者到桌面模式的steam里，清除下载缓存，看看能不能解决

**Comment by alwdark** [comment]
你好，調適工具中local storage找不到PowerControl的鍵，我用2.4.8下方的重置所有設定後移除重裝，問題依舊。
重開機後的第一次進入插件的設定頁因為perfStore.msgLimits與 perfStore.msgSettingsPerApp為undefined，必定出現steam載入圖。
重新載入插件，或是進入桌面模式再退出後才可進入設定頁。
但是因為2.4.5新增了載入設定出錯就會重置設定，因此每次設定都會被清除。

**Comment by honjow** [comment]
看看2.4.9正常了没

**Comment by alwdark** [comment]
你好，目前測試2.4.9重啟可以進入PowerControl設置頁，修改自訂義TDP也會生效。
但是又發生了issue描述的問題: TDP toggle會自己關掉；但是觀察是Patch造成的顯示問題，因為從mangohud看TDP限制是生效的。這也造成當不需要TDP限制時需要手動把TDP最大值拉到上限。

**Comment by honjow** [comment]
> 你好，目前測試2.4.9重啟可以進入PowerControl設置頁，修改自訂義TDP也會生效。 但是又發生了issue描述的問題: TDP toggle會自己關掉；但是觀察是Patch造成的顯示問題，因為從mangohud看TDP限制是生效的。這也造成當不需要TDP限制時需要手動把TDP最大值拉到上限。

搞不懂了。chimeraos stable版本吗？明天我装个看看

**Comment by alwdark** [comment]
你好，將v2.4.9 backend.ts line 406-407注釋掉，目前觀察正常。
有沒有可能tdp toggle的部分SteamOS會自己記錄，不需要額外patch?

**Comment by honjow** [comment]
> 你好，將v2.4.9 backend.ts line 406-407注釋掉，目前觀察正常。 有沒有可能tdp toggle的部分SteamOS會自己記錄，不需要額外patch?

这是为了在切换AC-电池模式配置的时候进行应用啊。。。我当然知道他会记录，但我两个模式有不同的tdp toggle，它如何切换？

**Comment by alwdark** [comment]
原來如此，我沒有測到電源模式變化的場景

**Comment by honjow** [comment]
> 原來如此，我沒有測到電源模式變化的場景

我安装了 chimeraos stable最新版本。依然没有复现这个问题。

**Comment by alwdark** [comment]
調試頁面中會看到這樣的日誌
![20240316_130615](https://github.com/mengmeet/PowerControl/assets/69226911/6500f5b3-9d54-406f-896e-79de3863c9cb)

**Comment by alwdark** [comment]
測試了2.4.10，真是非常多謝。
總之因不明原因，AppSettingData的TDPEnable會被改成false，因此Patch toggle TDP
![20240316_194443](https://github.com/mengmeet/PowerControl/assets/69226911/016c0722-52c4-4108-beec-1a6f3283823c)

**Comment by alwdark** [comment]
你好，重新安裝decky loader後，目前只有休眠喚醒或從桌面模式退回，enableTDP會被關掉，謝謝

**Comment by alwdark** [comment]
請問backend.ts line437優化GPU模式為Auto時，為何要將TDPEnable設定為false呢?

![2024-03-17 133317](https://github.com/mengmeet/PowerControl/assets/69226911/f3dc5995-f07d-4194-a3f1-d20b62e4d1f3)

**Comment by honjow** [comment]
> 請問backend.ts line437優化GPU模式為Auto時，為何要將TDPEnable設定為false呢?
> 
> ![2024-03-17 133317](https://private-user-images.githubusercontent.com/69226911/313447697-f3dc5995-f07d-4194-a3f1-d20b62e4d1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTM5MzMsIm5iZiI6MTcxMDY1MzYzMywicGF0aCI6Ii82OTIyNjkxMS8zMTM0NDc2OTctZjNkYzU5OTUtZjA3ZC00MTk0LWEzZjEtZDIwYjYyZTRkMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA1MzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTJhN2UzOTM3MmM4NTI1MjhkN2VjY2ZmMWVmY2VkOGExMDAzYWQ3NDc4YTc3OGEzYWEzMmU2ZWM1OTcyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJHGB48--BxELJ81RM3qCSm5k9bXQizGKaUZY2fbcWU)

因为设计就是这样啊。。不设置上限，仅通过关闭boost，和根据gpu负载调整频率。该用多少tdp就用多少
你想让tdp开关打开要么不控制gpu，让系统自己调整，要么就选范围

这个档位一直是这个逻辑，之前你没发现应该是因为tdp开关没有同步到qam而已

**Comment by honjow** [comment]
所以搞半天是因为这个啊。。。看来我要加点文字说明才行了

**Comment by alwdark** [comment]
了解了，非常多謝你
