### ISSUE TITLE
Steam spinning logo again since update 

### ISSUE THREAD

**Issue by ripplingsnake** [mengmeet/PowerControl#58]
Hello spinning steam logo on rog ally in decky is back again since update :)

**Comment by honjow** [comment]
Please try version 2.4.9 and see if it resolves the issue.

**Comment by ripplingsnake** [comment]
> Please try version 2.4.9 and see if it resolves the issue.

Hello yes all good again thank you

**Comment by stevefan1999-personal** [comment]
Same error starting from 2.4.20
